<?php
/**
 * Generated by framework installer - Sat, 15 Nov 2014 00:58:45 +0100
 */
    class Config
    {
	const BASEDNAME	= '/csc3123';
	const DBHOST	= 'localhost';
	const DB	= 'pensieve';
	const DBUSER	= 'root';
	const DBPW	= 'fingerprint';
	const SITENAME	= 'Pensieve';
	const SITEURL	= 'http://pensievelogbook.com';
	const SITENOREPLY	= 'j.a.morris@ncl.ac.uk';
	const SYSADMIN	= 'j.a.morris@ncl.ac.uk';
    }
?>